### ISSUE TITLE
A problem about running roms-wrf coupling model

### ISSUE THREAD

**Issue by wjlyx** [jcwarner-usgs/COAWST#293] opened 2024-08-08 03:35 UTC
Hello, I encountered the following issue while running the WRF-ROMS coupled model. Previously, it was showing 'max speed', but now it has suddenly changed to this error. How should I resolve it?

![image](https://github.com/user-attachments/assets/0e047771-d52a-4c05-bf7b-34a4cd17d440)
[slurm-25824.txt](https://github.com/user-attachments/files/16537208/slurm-25824.txt)
[Sandy_roms_grid.zip](https://github.com/user-attachments/files/16537213/Sandy_roms_grid.zip)
[ocean_sandy.txt](https://github.com/user-attachments/files/16537215/ocean_sandy.txt)
[namelist.input.txt](https://github.com/user-attachments/files/16537218/namelist.input.txt)

**Comment by wjlyx** [comment] 2024-08-08 07:05
> Hello, I encountered the following issue while running the WRF-ROMS coupled model. Previously, it was showing 'max speed', but now it has suddenly changed to this error. How should I resolve it?
> 
> ![image](https://private-user-images.githubusercontent.com/113485155/356073297-0e047771-d52a-4c05-bf7b-34a4cd17d440.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTUxOTUsIm5iZiI6MTcyMzA5NDg5NSwicGF0aCI6Ii8xMTM0ODUxNTUvMzU2MDczMjk3LTBlMDQ3NzcxLWQ1MmEtNGMwNS1iZjdiLTM0YTRjZDE3ZDQ0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwNTI4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjU3MDk4MzMzMjFiYmJhMDBlY2UwMzc1ZDU0MzgxN2RmNjAxNjUyMmM3ZGRhMTQ2MzE3MDdiYzU5ODYxNmMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R9QPWjaXGaBl3dF0BHFevVCE1nhzvbkNrsFBl3i98ww) [slurm-25824.txt](https://github.com/user-attachments/files/16537208/slurm-25824.txt) [Sandy_roms_grid.zip](https://github.com/user-attachments/files/16537213/Sandy_roms_grid.zip) [ocean_sandy.txt](https://github.com/user-attachments/files/16537215/ocean_sandy.txt) [namelist.input.txt](https://github.com/user-attachments/files/16537218/namelist.input.txt)

I changed the number of layers to N=25, and afterward, I encountered a max speed issue at the bottom layer(?). How should I handle this max speed issue at the bottom layer?
![image](https://github.com/user-attachments/assets/510e681d-9a42-41fb-863a-601edd948a98)
[slurm-25833.txt](https://github.com/user-attachments/files/16539048/slurm-25833.txt)

**Comment by jcwarner-usgs** [comment] 2024-08-08 12:50
in general, the steps would be to look at the rst file, determine where the issue is occurring.  Look at the his files, etc and get a feel for what the flow is doing. Is it the open boundary, along the land/sea mask, what is the bathy doing there, etc.  MAybe increase the visc from 1 to 2, etc.  
This Sandy case is a rather coarse setup, intended for training and not for realistic applications.  If you want to simulate this storm, i suggest you create a new grid that has more resolution.

**Comment by wjlyx** [comment] 2024-08-08 13:29
> in general, the steps would be to look at the rst file, determine where the issue is occurring. Look at the his files, etc and get a feel for what the flow is doing. Is it the open boundary, along the land/sea mask, what is the bathy doing there, etc. MAybe increase the visc from 1 to 2, etc. This Sandy case is a rather coarse setup, intended for training and not for realistic applications. If you want to simulate this storm, i suggest you create a new grid that has more resolution.

Thank you for your suggestions. Actually, I didn't fully use the Sandy case; I made some simple modifications based on it, such as using a 5km grid, setting the open and closed boundaries to West and North as Clo, and temperature and salinity as Gra. I tried time resolutions of 10s and 5s, but it still blows up at the same points. Does ROMS have specific requirements for the smoothing of nearshore bathymetry? I checked the rst file, and it shows that the horizontal gradients of temperature and salinity are relatively small in the first record, while the horizontal gradient of sea level is relatively high. Additionally, in the log, the max speed point shows a sustained surface current speed of around 8m/s, and the flow speed reached 8.5m/s just before the blow-up.

I have been troubled by this for a long time. Could you please provide some additional suggestions for modifications?

Here is the mask_rho map.The red dots indicate the approximate points where the blow-up occurs, at (184, 130) .
![image](https://github.com/user-attachments/assets/d1ac51c2-142f-46d6-b8da-3716ebac7fc1)

**Comment by jcwarner-usgs** [comment] 2024-08-08 14:58
looks like it is blowing up in a small coastal area.  that is only 1-2 grid cells wide.  so you are not resolving the flow there very well. 
I am not exactly sure what to do, but it is not resolving the coast well.  you will have to smooth the bathy in that area or make it more of a connection to the sea.

**Comment by wjlyx** [comment] 2024-08-09 09:27
> looks like it is blowing up in a small coastal area. that is only 1-2 grid cells wide. so you are not resolving the flow there very well. I am not exactly sure what to do, but it is not resolving the coast well. you will have to smooth the bathy in that area or make it more of a connection to the sea.

Thank you for your suggestions. I have resolved the issue.
![image](https://github.com/user-attachments/assets/3e143c84-ebbc-417e-ad60-9bb90282b55a)

**Comment by jcwarner-usgs** [comment] 2024-08-09 12:22
nice!

**Closed as completed by jcwarner-usgs** 2024-08-09 12:22 UTC
