### ISSUE TITLE
COAWSTV3.8 compile error with sandy.h, WRF+ROMS+SWAN

### ISSUE THREAD

**Issue by gutw** [jcwarner-usgs/COAWST#323] opened 2024-09-27 05:20 UTC
When I compiled COAWSTV3.8 with sandy.h, I can not generate coawstM[.exe]. There seems no obvious errors in build.log. I have tried many times including using default sandy.h and recompiled MCT. However, I never got coawstM[.exe]. Look forward for replying.

Here are relevant files.
(1)The header control file:
[sandy.h.log](https://github.com/user-attachments/files/17159366/sandy.h.log)

(2)The compile scripts:
[build_coawst.sh.log](https://github.com/user-attachments/files/17159356/build_coawst.sh.log)

(3)The compile environment:
[env.sh.log](https://github.com/user-attachments/files/17159358/env.sh.log)

(4)The compile log:
[build.log](https://github.com/user-attachments/files/17159361/build.log)

**Comment by jcwarner-usgs** [comment] 2024-09-27 13:38
the problem is that you are using pnetcdf for WRF.  A user has submitted a fix for this, but i have not tested it yet.
Instead, another fix is to remove the parallel netcdf path from your env.
try
export PNETCDF=""
you want it to be blank so wrf does not find it

**Comment by gutw** [comment] 2024-09-30 08:34
> the problem is that you are using pnetcdf for WRF. A user has submitted a fix for this, but i have not tested it yet. Instead, another fix is to remove the parallel netcdf path from your env. try export PNETCDF="" you want it to be blank so wrf does not find it

According to your advice, I generate coawstM[.exe] successfully.
Thanks a lot!

**Comment by jcwarner-usgs** [comment] 2024-09-30 12:29
nice!

**Closed as completed by jcwarner-usgs** 2024-09-30 12:29 UTC
